#include "aether12/collision.hpp"
#include "aether12/hardware.hpp"
#include "aether12/kinematics.hpp"
#include "aether12/safety.hpp"
#include "aether12/trajectory.hpp"

#include <cmath>
#include <cstdlib>
#include <iostream>
#include <string>

using namespace aether12;

namespace {

void require(bool condition, const std::string& message) {
  if (!condition) {
    std::cerr << "TEST FAILURE: " << message << '\n';
    std::exit(1);
  }
}

bool close(double first, double second, double tolerance = 1e-7) { return std::abs(first - second) <= tolerance; }

void testForwardKinematicsAndJacobian() {
  RobotModel model;
  Kinematics kinematics(model);
  std::array<double, kDof> joints{};
  const FKResult fk = kinematics.forwardKinematics(joints);
  require(fk.valid, "FK should accept the zero configuration");
  require(close(fk.pose.rotation[0][0] * fk.pose.rotation[0][0] + fk.pose.rotation[0][1] * fk.pose.rotation[0][1] + fk.pose.rotation[0][2] * fk.pose.rotation[0][2], 1.0, 1e-6), "rotation should remain normalized");
  const JacobianResult jacobian = kinematics.jacobian(joints);
  require(jacobian.valid, "Jacobian should be available at the zero configuration");
  for (const auto& row : jacobian.value) for (double value : row) require(std::isfinite(value), "Jacobian entries must be finite");
}

void testIK() {
  RobotModel model;
  Kinematics kinematics(model);
  std::array<double, kDof> target_joints{};
  target_joints[1] = 0.2; target_joints[2] = -0.25; target_joints[4] = 0.15;
  const FKResult target_fk = kinematics.forwardKinematics(target_joints);
  require(target_fk.valid, "target FK should succeed");
  std::array<double, kDof> initial{};
  const IKResult result = kinematics.inverseKinematics({target_fk.pose, false}, initial);
  require(result.converged, "redundant IK should converge to a pose generated by the same model");
  const FKResult solved_fk = kinematics.forwardKinematics(result.joints);
  require((solved_fk.pose.translation - target_fk.pose.translation).norm() < 2e-3, "IK position error should be small");
}

void testTrajectory() {
  RobotModel model;
  TrajectoryPlanner planner(model);
  std::array<double, kDof> start{};
  std::array<double, kDof> goal{};
  goal[0] = 0.3; goal[3] = -0.2;
  const JointTrajectory trajectory = planner.planJointSpace(start, goal, 2.0, 21);
  require(trajectory.valid, "quintic trajectory should be valid");
  require(trajectory.points.size() == 21, "trajectory should contain requested samples");
  require(close(trajectory.points.front().position[0], start[0]), "trajectory start position should match");
  require(close(trajectory.points.back().position[0], goal[0]), "trajectory goal position should match");
  require(close(trajectory.points.front().velocity[0], 0.0), "trajectory start velocity should be zero");
  require(close(trajectory.points.back().velocity[0], 0.0), "trajectory goal velocity should be zero");
}

void testCollisionAndSafety() {
  RobotModel model;
  CollisionChecker collision(model);
  const int obstacle_id = collision.addObstacle(SphereObstacle{{0.0, 0.0, 0.0}, 0.02});
  require(obstacle_id > 0, "obstacle should receive an id");
  const auto collision_result = collision.check({});
  require(collision_result.collision, "base obstacle should be detected");
  require(collision.removeObstacle(obstacle_id), "obstacle should be removable");

  SafetyManager safety(model);
  require(safety.transition(SafetyEvent::ConfigurationValid), "configuration should enter IDLE");
  require(safety.transition(SafetyEvent::Enable), "explicit enable should enter READY");
  require(safety.transition(SafetyEvent::BeginMotion), "begin motion should enter MOVING");
  std::array<double, kDof> velocity{};
  std::string error;
  require(safety.validateCommand({}, velocity, 0.01, &error), "valid command should pass safety checks");
  safety.latchEmergencyStop();
  require(safety.state() == SafetyState::Estop, "E-stop should latch");
  require(!safety.validateCommand({}, velocity, 0.01, &error), "commands should be rejected after E-stop");
  require(safety.transition(SafetyEvent::Reset), "manual reset should recover to IDLE");
  require(safety.state() == SafetyState::Idle, "reset should return to IDLE");
}

void testSimulationHardware() {
  SimulatedHardware hardware;
  std::string error;
  require(hardware.connect(&error), "simulated hardware should connect");
  require(hardware.enable(&error), "simulated hardware should enable");
  std::array<MotorCommand, kDof> commands{};
  for (auto& command : commands) { command.mode = ControlMode::Position; command.target_position = 0.25; }
  require(hardware.sendJointCommands(commands, &error), "valid position commands should be accepted");
  hardware.update(0.1);
  require(hardware.readJointStates()[0].position > 0.0, "simulation should move toward the command");
  hardware.emergencyStop();
  require(!hardware.sendJointCommands(commands, &error), "commands should be rejected after simulated E-stop");
}

}  // namespace

int main() {
  testForwardKinematicsAndJacobian();
  testIK();
  testTrajectory();
  testCollisionAndSafety();
  testSimulationHardware();
  std::cout << "AETHER-12 core tests passed\n";
  return 0;
}
